services:
  design-workflow-tracker:
    build:
      context: .
    container_name: design-workflow-tracker
    restart: always
    env_file:
      - .env
    environment:
      APP_ENV: production
      APP_DEBUG: 'false'
      APP_URL: https://portal.ptbmi.com/design-workflow-tracker
      ASSET_URL: https://portal.ptbmi.com/design-workflow-tracker
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.design-workflow-tracker.rule=Host(`portal.ptbmi.com`) && PathPrefix(`/design-workflow-tracker`)'
      - 'traefik.http.routers.design-workflow-tracker.entrypoints=websecure'
      - 'traefik.http.routers.design-workflow-tracker.tls=true'
      - 'traefik.http.services.design-workflow-tracker.loadbalancer.server.port=80'
      - 'traefik.http.middlewares.design-workflow-tracker-strip.stripprefix.prefixes=/design-workflow-tracker'
      - 'traefik.http.routers.design-workflow-tracker.middlewares=design-workflow-tracker-strip'
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true
